apiVersion: v1
kind: Service
metadata:
  name: timeoff-management
spec:
  type: LoadBalancer
  selector:
    app: timeoff-management
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-management
spec:
  selector:
    matchLabels:
      app: timeoff-management
  template:
    metadata:
      labels:
        app: timeoff-management
    spec:
      containers:
        - name: timeoff-management
          image: luongdang/morningstar-timeoff-management:1.4.3
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeoff-management-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: timeoff-management
                port:
                  number: 80
      host: agates.canadacentral.cloudapp.azure.com
  tls:
    - hosts:
        - agates.canadacentral.cloudapp.azure.com
