apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: luong.dang@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: my-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   rules:
#     - host: a7f5717a8867e45bd890a13c9da28074-1492914715.ca-central-1.elb.amazonaws.com
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: my-service
#               servicePort: 80
#   tls:
#     - hosts:
#       - a7f5717a8867e45bd890a13c9da28074-1492914715.ca-central-1.elb.amazonaws.com
