# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

name: 1.0$(Rev:.r)
trigger: 
  branches:
    include:
      - main
      - pipelines # TODO: remove this
  paths:
    include:
      - cluster/morningstar.yml
      - pipelines/cluster.yml # TODO: remove this

parameters:
  - name: create_cluster
    displayName: Create new cluster
    type: boolean
    default: "false"

variables: 
  group: AWS Credentials

stages:
  - stage: create_cluster
    displayName: Create Cluster
    condition: eq('${{ parameters.create_cluster }}', 'true')
    jobs:
      - job: create_cluster
        displayName: Create Cluster
        steps:
          - template: configure_aws.yml
          - bash: |
              eksctl create cluster -f cluster/morningstar.yml

  - stage: update_cluster
    displayName: Update Cluster
    condition: eq('${{ parameters.create_cluster }}', 'false')
    jobs:
      - job: update_cluster
        displayName: Update Cluster
        steps:
          - template: configure_aws.yml
          - bash: |
              # eksctl upgrade cluster -f cluster/morningstar.yml
              echo "Should do something here"
            displayName: Update Cluster
