# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

# This pipeline delivers changes to the EKS cluster. 
# To update the Timeoff Management app, use the `app.yml` pipeline.
#
# There are 3 execution modes:
#   - create: create the cluster on EKS
#   - update: update the existing cluster
#   - delete: remove the cluster from EKS
#
# The default mode is `update`, which will be trigger automatically upon every
# changes to `cluster` folder. `create` and `delete` can be triggered
# automatically, since they are expected to run far less often than `update`.

name: 1.0$(Rev:.r)
trigger:
  branches:
    include:
      - main
      - pipelines # TODO: remove this
  paths:
    include:
      - cluster/*
      - pipelines/cluster.yml # TODO: remove this

parameters:
  - name: mode
    displayName: Mode
    type: string
    values:
      - create
      - update
      - delete
    default: update

variables:
  - group: aws-credentials

stages:
  - stage: cluster_action
    displayName: Cluster Action
    jobs:
      - job: create_cluster
        condition: eq('${{ parameters.mode }}', 'create')
        displayName: Create Cluster
        steps:
          - template: steps_configure_aws.yml
          - bash: eksctl create cluster -f cluster/morningstar.yml
            displayName: Create Cluster
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - job: update_cluster
        displayName: Update Cluster
        condition: eq('${{ parameters.mode }}', 'update')
        steps:
          - template: steps_configure_aws.yml
          - bash: |
              set -xueo pipefail
              eksctl upgrade cluster -f cluster/morningstar.yml --approve
              eksctl update iamserviceaccount -f cluster/morningstar.yml --approve
            displayName: Update Cluster
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - job: delete_cluster
        displayName: Delete Cluster
        condition: eq('${{ parameters.mode }}', 'delete')
        steps:
          - template: steps_configure_aws.yml
          - bash: |
              set -xueo pipefail

              kubectl delete namespace app
              eksctl delete cluster -f cluster/morningstar.yml
            displayName: Delete Cluster
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
