# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

name: 1.0$(Rev:.r)
trigger: 
  branches:
    include:
      - main
      - pipelines # TODO: remove this
  paths:
    include:
      - cluster/morningstar.yml
      - pipelines/cluster.yml # TODO: remove this

parameters:
  - name: mode
    displayName: Mode
    type: string
    values:
      - create
      - update
      - delete
    default: update

variables: 
  group: aws-credentials

stages:
  - stage: create_cluster
    displayName: Create Cluster
    condition: eq('${{ parameters.mode }}', 'create')
    jobs:
      - job: create_cluster
        displayName: Create Cluster
        steps:
          - template: configure_aws.yml
          - bash: eksctl create cluster -f cluster/morningstar.yml
            displayName: Crate Cluster

  - stage: update_cluster
    displayName: Update Cluster
    condition: eq('${{ parameters.mode }}', 'update')
    jobs:
      - job: update_cluster
        displayName: Update Cluster
        steps:
          - bash: env
            displayName: debug
            env:
              AWS_ACCESS_KEY_ID: $[variables.AWS_ACCESS_KEY_ID]
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

          - template: configure_aws.yml
          - bash: eksctl upgrade cluster -f cluster/morningstar.yml
            displayName: Update Cluster
          - bash: eksctl update nodegroup -f cluster/morningstar.yml
            displayName: Update Nodegroup
          - bash: eksctl update iamserviceaccount -f cluster/morningstar.yml
            displayName: Update Service Accounts
          
