# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

steps:
  - bash: aws configure list
    displayName: Show AWS Config
    env:
      AWS_ACCESS_KEY_ID: $[variables.AWS_ACCESS_KEY_ID]
      AWS_SECRET_ACCESS_KEY: $[AWS_SECRET_ACCESS_KEY]
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

  - bash: |
      set -xueo pipefail

      curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      sudo mv /tmp/eksctl /usr/local/bin
      echo "eksctl version = $(eksctl version)"
    displayName: Install eksctl
