# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

steps:
  - bash: |
      set -xueo pipefail
      
      curl -sL "https://github.com/weaveworks/eksctl/releases/download/v0.130.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      sudo mv /tmp/eksctl /usr/local/bin
      echo "eksctl version = $(eksctl version)"
    displayName: Install eksctl

  - bash: |
      set -xueo pipefail

      eksctl utils write-kubeconfig -f cluster/morningstar.yml || :
      kubectl config current-context || :
    displayName: Set kubectl config
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
